name: opencode winget update

on:
  issues:
    types: [opened, reopened]

jobs:
  opencode:
    if: contains(github.event.issue.title, '[winget-update]')
    runs-on: windows-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          winget install -e --id RussellBanks.Komac -s winget
          winget install -e --id Microsoft.WingetCreate -s winget
          winget install -e --id SST.opencode -s winget
  
      - name: Run OpenCode
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          $full_prompt = "/winget-update`n`n" + $env:ISSUE_BODY
          opencode run "$full_prompt" --dangerously-skip-permissions
      
      - run: tree /F

      - name: Submit Manifest
        run: python find_manifest_and_submit.py ${{ secrets.TOKEN }}
